package:
  name: conda
  version: 4.4.3

source:
  git_url: https://github.com/conda/conda.git
  git_rev: 2060458e0c546a3c70fa041e738cb73b41c4b0d3  # 4.4.3

build:
  number: 0
  # These are present when the new environment is created
  # so we have to exempt them from the list of initial files
  # for conda-build to realize they should be included.
  always_include_files:
    - bin/conda                            # [unix]
    - bin/activate                         # [unix]
    - bin/deactivate                       # [unix]
    - Scripts/activate.bat                 # [win]
    - Scripts/activate                     # [win]
    - Scripts/deactivate.bat               # [win]
    - Scripts/deactivate                   # [win]
  entry_points:
    - conda = conda.cli:main
    - conda-env = conda_env.cli.main:main

requirements:
  host:
    - python
    - m2-base              [win]
    - m2-filesystem        [win]
    - m2-git               [win]
    - pycosat
    - pyopenssl
    - requests
    - ruamel_yaml
  run:
    - python
    - conda-env >=2.6
    - enum34               [py<34]
    - futures              [py<34]
    - menuinst             [win]
    - pycosat >=0.6.3
    - pyopenssl >=16.2.0
    - requests >=2.14.2,<3
    - ruamel_yaml >=0.11.14
  run_constrained:
    - conda-build >=2.1
    - cytoolz >=0.8.1

test:
  requires:
    - mock
    - pytest
    - pytest-cov
  imports:
    - conda
    - conda.exports
    - conda_env
  commands:
    # Check version via import.
    - python -c "import conda; print(conda.__version__)"

    # Show where the conda commands are.
    - which conda                  # [unix]
    - where conda                  # [win]
    - which conda-env              # [unix]
    - where conda-env              # [win]

    # Run some simple conda commands.
    - conda --version
    - conda info --all
    - conda env --help

    # # Conda's unit tests
    # can't do this because SRC_DIR gets removed after the build step?
    # - py.test -m "not integration and not installed" $SRC_DIR/tests $SRC_DIR/conda    # [unix]
    # - py.test -m "not integration and not installed" %SRC_DIR%/tests %SRC_DIR%/conda  # [win]

about:
  home: https://conda.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: OS-agnostic, system-level binary package and environment manager.
  description: |
    Conda is an open source package management system and environment
    management system for installing multiple versions of software packages
    and their dependencies and switching easily between them. It works on
    Linux, OS X and Windows, and was created for Python programs but can
    package and distribute any software.
  doc_url: https://conda.io/docs/
  dev_url: https://github.com/conda/conda

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
