travis:
  secure:
    BINSTAR_TOKEN: U7TmzoGIg7T7KLJgzxvsXYwWC8P/Za6An7u0YqHjzwTpG67VV1kcciJWyveom2upc1uBoLbo17KAzHscFOM9eXuFmPaS5FMIAPhZo10gAtuErHNm1wj7pApJcDUU4kwNIRmUH8v3V1RMkn3ukNgq44L0Dl0/PReFPbRQD3ARpyP85s4O8vZZtncMMGzmS40hHWUMDqbXGCylsJWU3WGKymEnkF90GvcCO0lDf7ilVYXMv/d4uXGzzzqS/8H8k4AVdldb+628Y959fySZplZwU9AWRzwXoluM+TRv+mMvMiUpGkkrxdFBNXDk8HfyxsHEm47R+k0Fis7VjotEPVbf++2Ulm3auBzkxHtYG26VUniieSceNu2qRmw69W343AGmUATBqIcVfZMTc4vyrcNGT0Y2RIfQY3mJG1I/aUJgytiyZbjL+pnisdZP2JqD58KahRBcNld2XWmUOT3v5iHj0iAk/dshIEaSPdxPGswwyokRtROxAbuzGdNaX8ttJIZ7jzBvG0prHtJqNpr+JscCC6tY0hOXNQuSUj7tQReR+VVTr1rMaN3qIIz/i7/09v4faxNiygyobJoXOF23qQbR0tZMDEUiP+Ub5yGGAG4ziCpxyLfHgYa/FNPXnGx7dSQK6HtxHludxAT7Cj7GDXMSBiO0IcxEbb//jyXyz6gA7Fk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
